package gamedata

import "fmt"

// 未對上(需人工核對):
// TECH_HYPER_BIOLOGY(值 204):候選 "Hyper Biology" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串
// TECH_HYPER_POWER(值 205):候選 "Hyper Power" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串
// TECH_HYPER_PHYSICS(值 206):候選 "Hyper Physics" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串
// TECH_HYPER_CONSTRUCTION(值 207):候選 "Hyper Construction" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串
// TECH_HYPER_FIELDS(值 208):候選 "Hyper Fields" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串
// TECH_HYPER_CHEMISTRY(值 209):候選 "Hyper Chemistry" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串
// TECH_HYPER_COMPUTERS(值 210):候選 "Hyper Computers" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串
// TECH_HYPER_SOCIOLOGY(值 211):候選 "Hyper Sociology" — openorion2 TOPIC_HYPER_* 未來研究佔位,無 TECHNAME.LBX 對應顯示字串

// TechnologyNames:Technology -> 英文名(對應 TECHNAME.LBX / tech.tsv key)。
// 機械轉寫自 enums.go 常數名 + tech.tsv 驗證(2026-07-10)。
// 連字號拼寫(Anti-Grav / Anti-Matter / Bio-Terminator 等)已人工核對 tech.tsv 實際 key。
var TechnologyNames = map[Technology]string{
	TECH_ACHILLES_TARGETING_UNIT:     "Achilles Targeting Unit",
	TECH_ADAMANTIUM_ARMOR:            "Adamantium Armor",
	TECH_ADVANCED_CITY_PLANNING:      "Advanced City Planning",
	TECH_ADVANCED_DAMAGE_CONTROL:     "Advanced Damage Control",
	TECH_ALIEN_MANAGEMENT_CENTER:     "Alien Management Center",
	TECH_ANDROID_FARMERS:             "Android Farmers",
	TECH_ANDROID_SCIENTISTS:          "Android Scientists",
	TECH_ANDROID_WORKERS:             "Android Workers",
	TECH_ANTIGRAV_HARNESS:            "Anti-Grav Harness",
	TECH_ANTIMATTER_BOMB:             "Anti-Matter Bomb",
	TECH_ANTIMATTER_DRIVE:            "Anti-Matter Drive",
	TECH_ANTIMATTER_TORPEDOES:        "Anti-Matter Torpedoes",
	TECH_ANTIMISSILE_ROCKETS:         "Anti-Missile Rockets",
	TECH_ARMOR_BARRACKS:              "Armor Barracks",
	TECH_ARTEMIS_SYSTEM_NET:          "Artemis System Net",
	TECH_PLANET_CONSTRUCTION:         "Planet Construction",
	TECH_ASSAULT_SHUTTLES:            "Assault Shuttles",
	TECH_ASTRO_UNIVERSITY:            "Astro University",
	TECH_ATMOSPHERIC_RENEWER:         "Atmospheric Renewer",
	TECH_AUGMENTED_ENGINES:           "Augmented Engines",
	TECH_AUTOLAB:                     "Autolab",
	TECH_AUTOMATED_FACTORIES:         "Automated Factories",
	TECH_AUTOMATED_REPAIR_UNIT:       "Automated Repair Unit",
	TECH_BATTLEOIDS:                  "Battleoids",
	TECH_BATTLE_PODS:                 "Battle Pods",
	TECH_BATTLE_SCANNER:              "Battle Scanner",
	TECH_BATTLESTATION:               "Battlestation",
	TECH_BIOTERMINATOR:               "Bio-Terminator",
	TECH_BIOMORPHIC_FUNGI:            "Biomorphic Fungi",
	TECH_BLACK_HOLE_GENERATOR:        "Black Hole Generator",
	TECH_BOMBER_BAYS:                 "Bomber Bays",
	TECH_CAPITOL:                     "Capitol",
	TECH_CLASS_I_SHIELD:              "Class I Shield",
	TECH_CLASS_III_SHIELD:            "Class III Shield",
	TECH_CLASS_V_SHIELD:              "Class V Shield",
	TECH_CLASS_VII_SHIELD:            "Class VII Shield",
	TECH_CLASS_X_SHIELD:              "Class X Shield",
	TECH_CLOAKING_DEVICE:             "Cloaking Device",
	TECH_CLONING_CENTER:              "Cloning Center",
	TECH_COLONY_BASE:                 "Colony Base",
	TECH_COLONY_SHIP:                 "Colony Ship",
	TECH_CONFEDERATION:               "Confederation",
	TECH_CYBERSECURITY_LINK:          "Cyber-Security Link",
	TECH_CYBERTRONIC_COMPUTER:        "Cybertronic Computer",
	TECH_DAMPER_FIELD:                "Damper Field",
	TECH_DAUNTLESS_GUIDANCE_SYSTEM:   "Dauntless Guidance System",
	TECH_DEATH_RAY:                   "Death Ray",
	TECH_DEATH_SPORES:                "Death Spores",
	TECH_DEEP_CORE_MINING:            "Deep Core Mining",
	TECH_CORE_WASTE_DUMPS:            "Core Waste Dumps",
	TECH_DEUTERIUM_FUEL_CELLS:        "Deuterium Fuel Cells",
	TECH_DIMENSIONAL_PORTAL:          "Dimensional Portal",
	TECH_DISPLACEMENT_DEVICE:         "Displacement Device",
	TECH_DISRUPTER_CANNON:            "Disrupter Cannon",
	TECH_DOOM_STAR_CONSTRUCTION:      "Doom Star Construction",
	TECH_REINFORCED_HULL:             "Reinforced Hull",
	TECH_ECM_JAMMER:                  "Ecm Jammer",
	TECH_ELECTRONIC_COMPUTER:         "Electronic Computer",
	TECH_EMISSIONS_GUIDANCE_SYSTEM:   "Emissions Guidance System",
	TECH_ENERGY_ABSORBER:             "Energy Absorber",
	TECH_BIOSPHERES:                  "Biospheres",
	TECH_EVOLUTIONARY_MUTATION:       "Evolutionary Mutation",
	TECH_EXTENDED_FUEL_TANKS:         "Extended Fuel Tanks",
	TECH_FAST_MISSILE_RACKS:          "Fast Missile Racks",
	TECH_FEDERATION:                  "Federation",
	TECH_FIGHTER_BAYS:                "Fighter Bays",
	TECH_FIGHTER_GARRISON:            "Fighter Garrison",
	TECH_FOOD_REPLICATORS:            "Food Replicators",
	TECH_FREIGHTERS:                  "Freighters",
	TECH_FUSION_BEAM:                 "Fusion Beam",
	TECH_FUSION_BOMB:                 "Fusion Bomb",
	TECH_FUSION_DRIVE:                "Fusion Drive",
	TECH_FUSION_RIFLE:                "Fusion Rifle",
	TECH_GAIA_TRANSFORMATION:         "Gaia Transformation",
	TECH_GALACTIC_CURRENCY_EXCHANGE:  "Galactic Currency Exchange",
	TECH_GALACTIC_CYBERNET:           "Galactic Cybernet",
	TECH_GALACTIC_UNIFICATION:        "Galactic Unification",
	TECH_GAUSS_CANNON:                "Gauss Cannon",
	TECH_GRAVITON_BEAM:               "Graviton Beam",
	TECH_GYRO_DESTABILIZER:           "Gyro Destabilizer",
	TECH_HARD_SHIELDS:                "Hard Shields",
	TECH_HEAVY_ARMOR:                 "Heavy Armor",
	TECH_HEAVY_FIGHTER_BAYS:          "Heavy Fighter Bays",
	TECH_HEIGHTENED_INTELLIGENCE:     "Heightened Intelligence",
	TECH_HIGH_ENERGY_FOCUS:           "High Energy Focus",
	TECH_HOLO_SIMULATOR:              "Holo Simulator",
	TECH_HYDROPONIC_FARM:             "Hydroponic Farm",
	TECH_HYPER_DRIVE:                 "Hyper Drive",
	TECH_MEGAFLUXERS:                 "Megafluxers",
	TECH_HYPERX_CAPACITORS:           "Hyper-X Capacitors",
	TECH_HYPERSPACE_COMMUNICATIONS:   "Hyperspace Communications",
	TECH_IMPERIUM:                    "Imperium",
	TECH_INERTIAL_NULLIFIER:          "Inertial Nullifier",
	TECH_INERTIAL_STABILIZER:         "Inertial Stabilizer",
	TECH_INTERPHASED_DRIVE:           "Interphased Drive",
	TECH_ION_DRIVE:                   "Ion Drive",
	TECH_ION_PULSE_CANNON:            "Ion Pulse Cannon",
	TECH_IRIDIUM_FUEL_CELLS:          "Iridium Fuel Cells",
	TECH_JUMP_GATE:                   "Jump Gate",
	TECH_LASER_CANNON:                "Laser Cannon",
	TECH_LASER_RIFLE:                 "Laser Rifle",
	TECH_LIGHTNING_FIELD:             "Lightning Field",
	TECH_MARINE_BARRACKS:             "Marine Barracks",
	TECH_MASS_DRIVER:                 "Mass Driver",
	TECH_MAULER_DEVICE:               "Mauler Device",
	TECH_MERCULITE_MISSILE:           "Merculite Missile",
	TECH_MICROBIOTICS:                "Microbiotics",
	TECH_MICROLITE_CONSTRUCTION:      "Microlite Construction",
	TECH_OUTPOST_SHIP:                "Outpost Ship",
	TECH_MOLECULARTRONIC_COMPUTER:    "Moleculartronic Computer",
	TECH_MULTIWAVE_ECM_JAMMER:        "Multi-Wave Ecm Jammer",
	TECH_MULTIPHASED_SHIELDS:         "Multi-Phased Shields",
	TECH_NANO_DISASSEMBLERS:          "Nano Disassemblers",
	TECH_NEURAL_SCANNER:              "Neural Scanner",
	TECH_NEUTRON_BLASTER:             "Neutron Blaster",
	TECH_NEUTRON_SCANNER:             "Neutron Scanner",
	TECH_NEUTRONIUM_ARMOR:            "Neutronium Armor",
	TECH_NEUTRONIUM_BOMB:             "Neutronium Bomb",
	TECH_NUCLEAR_BOMB:                "Nuclear Bomb",
	TECH_NUCLEAR_DRIVE:               "Nuclear Drive",
	TECH_NUCLEAR_MISSILE:             "Nuclear Missile",
	TECH_OPTRONIC_COMPUTER:           "Optronic Computer",
	TECH_PARTICLE_BEAM:               "Particle Beam",
	TECH_PERSONAL_SHIELD:             "Personal Shield",
	TECH_PHASE_SHIFTER:               "Phase Shifter",
	TECH_PHASING_CLOAK:               "Phasing Cloak",
	TECH_PHASOR:                      "Phasor",
	TECH_PHASOR_RIFLE:                "Phasor Rifle",
	TECH_PLANETARY_BARRIER_SHIELD:    "Planetary Barrier Shield",
	TECH_PLANETARY_FLUX_SHIELD:       "Planetary Flux Shield",
	TECH_PLANETARY_GRAVITY_GENERATOR: "Planetary Gravity Generator",
	TECH_PLANETARY_MISSILE_BASE:      "Planetary Missile Base",
	TECH_GROUND_BATTERIES:            "Ground Batteries",
	TECH_PLANETARY_RADIATION_SHIELD:  "Planetary Radiation Shield",
	TECH_PLANETARY_STOCK_EXCHANGE:    "Planetary Stock Exchange",
	TECH_PLANETARY_SUPERCOMPUTER:     "Planetary Supercomputer",
	TECH_PLASMA_CANNON:               "Plasma Cannon",
	TECH_PLASMA_RIFLE:                "Plasma Rifle",
	TECH_PLASMA_TORPEDOES:            "Plasma Torpedoes",
	TECH_PLASMA_WEB:                  "Plasma Web",
	TECH_PLEASURE_DOME:               "Pleasure Dome",
	TECH_POLLUTION_PROCESSOR:         "Pollution Processor",
	TECH_POSITRONIC_COMPUTER:         "Positronic Computer",
	TECH_POWERED_ARMOR:               "Powered Armor",
	TECH_PULSE_RIFLE:                 "Pulse Rifle",
	TECH_PROTON_TORPEDOES:            "Proton Torpedoes",
	TECH_PSIONICS:                    "Psionics",
	TECH_PULSAR:                      "Pulsar",
	TECH_PULSON_MISSILE:              "Pulson Missile",
	TECH_QUANTUM_DETONATOR:           "Quantum Detonator",
	TECH_RANGEMASTER_UNIT:            "Rangemaster Unit",
	TECH_RECYCLOTRON:                 "Recyclotron",
	TECH_REFLECTION_FIELD:            "Reflection Field",
	TECH_ROBOTIC_FACTORY:             "Robotic Factory",
	TECH_RESEARCH_LABORATORY:         "Research Laboratory",
	TECH_ROBOMINERS:                  "Robo-Miners",
	TECH_SPACE_SCANNER:               "Space Scanner",
	TECH_SCOUT_LAB:                   "Scout Lab",
	TECH_SECURITY_STATIONS:           "Security Stations",
	TECH_SENSORS:                     "Sensors",
	TECH_SHIELD_CAPACITORS:           "Shield Capacitors",
	TECH_SOIL_ENRICHMENT:             "Soil Enrichment",
	TECH_SPACE_ACADEMY:               "Space Academy",
	TECH_SPACEPORT:                   "Spaceport",
	TECH_SPATIAL_COMPRESSOR:          "Spatial Compressor",
	TECH_SPY_NETWORK:                 "Spy Network",
	TECH_STANDARD_FUEL_CELLS:         "Standard Fuel Cells",
	TECH_STAR_BASE:                   "Star Base",
	TECH_STAR_FORTRESS:               "Star Fortress",
	TECH_STAR_GATE:                   "Star Gate",
	TECH_STASIS_FIELD:                "Stasis Field",
	TECH_STEALTH_FIELD:               "Stealth Field",
	TECH_STEALTH_SUIT:                "Stealth Suit",
	TECH_STELLAR_CONVERTER:           "Stellar Converter",
	TECH_STRUCTURAL_ANALYZER:         "Structural Analyzer",
	TECH_SUBSPACE_COMMUNICATIONS:     "Sub-Space Communications",
	TECH_SUBSPACE_TELEPORTER:         "Sub-Space Teleporter",
	TECH_SUBTERRANEAN_FARMS:          "Subterranean Farms",
	TECH_SURVIVAL_PODS:               "Survival Pods",
	TECH_TACHYON_COMMUNICATIONS:      "Tachyon Communications",
	TECH_TACHYON_SCANNER:             "Tachyon Scanner",
	TECH_TELEPATHIC_TRAINING:         "Telepathic Training",
	TECH_TERRAFORMING:                "Terraforming",
	TECH_THORIUM_FUEL_CELLS:          "Thorium Fuel Cells",
	TECH_TIME_WARP_FACILITATOR:       "Time Warp Facilitator",
	TECH_TITAN_CONSTRUCTION:          "Titan Construction",
	TECH_TITANIUM_ARMOR:              "Titanium Armor",
	TECH_TRACTOR_BEAM:                "Tractor Beam",
	TECH_TRANSPORT:                   "Transport",
	TECH_TRANSPORTERS:                "Transporters",
	TECH_TRITANIUM_ARMOR:             "Tritanium Armor",
	TECH_TROOP_PODS:                  "Troop Pods",
	TECH_UNIVERSAL_ANTIDOTE:          "Universal Antidote",
	TECH_URRIDIUM_FUEL_CELLS:         "Urridium Fuel Cells",
	TECH_VIRTUAL_REALITY_NETWORK:     "Virtual Reality Network",
	TECH_WARP_DISSIPATER:             "Warp Dissipater",
	TECH_WARP_INTERDICTOR:            "Warp Interdictor",
	TECH_WEATHER_CONTROL_SYSTEM:      "Weather Control System",
	TECH_WIDE_AREA_JAMMER:            "Wide Area Jammer",
	TECH_XENO_PSYCHOLOGY:             "Xeno Psychology",
	TECH_XENTRONIUM_ARMOR:            "Xentronium Armor",
	TECH_ZEON_MISSILE:                "Zeon Missile",
	TECH_ZORTRIUM_ARMOR:              "Zortrium Armor",
}

// TechnologyName 回傳英文名,查無回 fmt.Sprintf("Tech#%d", ...)。
func TechnologyName(t Technology) string {
	if name, ok := TechnologyNames[t]; ok {
		return name
	}
	return fmt.Sprintf("Tech#%d", int(t))
}
