package shell

// shipnames.go:原版 SHIPNAME.LBX asset0 的 672 條艦名池,**依原始索引順序,存英文原文**
// (含重複,如結尾一批 Avenger)。新造艦命名依 `shipNamePool[全帝國艦數 % 672]` 循環取用。
//
// ⚠ 2026-08-08(第 84 項(名稱池雙語化))把這個池從中文改成英文,理由同 starnames.go:
// 池子存中文的話英文模式會出現中文艦名,而那補不回來。中文由 `GameSession.TranslateName`
// 在**造艦時**翻,所以中文模式輸出不變。
//
// 翻譯方案見 docs/tech/proper-noun-strategy.md(基底詞意譯 + 羅馬數字流水號原樣保留)。
// 英文池是從先前的中文池反查還原的:`assets/i18n/shipname.tsv` 的中文→英文反查
// **零歧義、零缺漏**,還原唯一。
var shipNamePool = []string{
	"Sparrow I",
	"Starling",
	"Pin Feather",
	"Striker",
	"Soarer",
	"Swiftwing",
	"Fisher",
	"Thrush",
	"Hawk I",
	"Hawk II",
	"Hawk III",
	"Goshawk",
	"Sharpbeak",
	"Bloodfoot",
	"Blackhawk",
	"Red Wing",
	"Falcon I",
	"Falcon II",
	"Falcon III",
	"Falcon IV",
	"Falcon V",
	"Falcon VI",
	"Falcon VII",
	"Peregrine",
	"Dreadwing I",
	"Dreadwing II",
	"Dreadwing III",
	"Dreadwing IV",
	"Dreadwing V",
	"Dreadwing VI",
	"Dreadwing VII",
	"Dreadwing VIII",
	"Phoenix",
	"War Eagle",
	"Pegasus",
	"Roc",
	"Quetzicoatl",
	"Foe Render",
	"Wyvern",
	"Condor",
	"Dragon",
	"Dragon",
	"Dragon",
	"Dragon",
	"Dragon",
	"Dragon",
	"Dragon",
	"Dragon",
	"Claw I",
	"Claw II",
	"Claw III",
	"Panda",
	"Cub",
	"Swiftpaw",
	"Biter",
	"Fang",
	"Wolverine I",
	"Wolverine II",
	"Wolverine III",
	"Wolverine IV",
	"Wolverine V",
	"Wolverine VI",
	"Wolverine VII",
	"Wolverine VII",
	"Coyote I",
	"Coyote II",
	"Coyote III",
	"Coyote IV",
	"Coyote V",
	"Coyote VI",
	"Coyote VII",
	"Coyote VII",
	"Wolf I",
	"Wolf II",
	"Wolf III",
	"Wolf IV",
	"Wolf V",
	"Wolf VI",
	"Wolf VII",
	"Wolf VII",
	"Ursus",
	"Cave Bear",
	"GrizzlyBear",
	"Warbear I",
	"Warbear II",
	"Warbear III",
	"Warbear IV",
	"Warbear V",
	"Kodiak",
	"Kodiak",
	"Kodiak",
	"Kodiak",
	"Kodiak",
	"Kodiak",
	"Kodiak",
	"Kodiak",
	"Comet I",
	"Comet II",
	"Comet III",
	"Comet IV",
	"Comet V",
	"Comet VI",
	"Asteriod",
	"Meteor",
	"Seeker I",
	"Seeker II",
	"Seeker III",
	"Seeker IV",
	"Seeker V",
	"Seeker VI",
	"Seeker VII",
	"Seeker VIII",
	"Corona I",
	"Corona II",
	"Corona III",
	"Corona IV",
	"Corona V",
	"Corona VI",
	"Corona VII",
	"Corona VIII",
	"StarStreak I",
	"StarStreak II",
	"StarStreak III",
	"StarStreak IV",
	"StarStreak V",
	"StarStreak VI",
	"StarStreak VII",
	"StarStreak VIII",
	"Sun Fire I",
	"Sun Fire II",
	"Sun Fire III",
	"Sun Fire IV",
	"Sun Fire V",
	"Sun Fire VI",
	"Sun Fire VII",
	"Sun Fire VIII",
	"Nova",
	"Nova",
	"Nova",
	"Nova",
	"Nova",
	"Nova",
	"Nova",
	"Nova",
	"Dagger",
	"Main Gauche",
	"Skein Dbuh",
	"Kris",
	"Stiletto",
	"Carraca",
	"Shurikin",
	"Katar",
	"Falcata",
	"War Hammer",
	"Flail",
	"Bola",
	"Cinqueda",
	"Dirk",
	"Mace",
	"Gladius",
	"Cutlass",
	"Tachi",
	"Karabela",
	"Rapier",
	"Backsword",
	"Scimitar",
	"Katana",
	"Tachi",
	"Sabre",
	"Claymore",
	"Pike",
	"War Hammer",
	"Katana",
	"Locaber",
	"Pikemaul",
	"Halberd",
	"Dark Blade",
	"Catapult",
	"Seibe Bow",
	"Trebuchet",
	"Balista",
	"Malvosin",
	"Cannonade",
	"Falchard",
	"Excaliber",
	"Excaliber",
	"Excaliber",
	"Excaliber",
	"Excaliber",
	"Excaliber",
	"Excaliber",
	"Excaliber",
	"Sprite I",
	"Sprite II",
	"Sprite III",
	"Sprite IV",
	"Sprite V",
	"Sprite VI",
	"Sprite VII",
	"Nymph",
	"Gremlin I",
	"Gremlin II",
	"Gremlin III",
	"Gremlin IV",
	"Gremlin V",
	"Gremlin VI",
	"Gremlin VII",
	"Gremlin VIII",
	"Goblin I",
	"Goblin II",
	"Goblin III",
	"Goblin IV",
	"Goblin V",
	"Goblin VI",
	"Goblin VII",
	"Goblin VIII",
	"Ogre I",
	"Ogre II",
	"Ogre III",
	"Ogre IV",
	"Ogre V",
	"Ogre VI",
	"Ogre VII",
	"Ogre VIII",
	"Troll I",
	"Troll II",
	"Troll III",
	"Troll IV",
	"Troll V",
	"Troll VI",
	"Troll VII",
	"Troll VIII",
	"Demon",
	"Demon",
	"Demon",
	"Demon",
	"Demon",
	"Demon",
	"Demon",
	"Demon",
	"Gripen",
	"Lark",
	"Wildcat",
	"Spitfire",
	"Oasis",
	"Mustang",
	"Cheetah",
	"Thunderbolt",
	"Rafale",
	"Draken",
	"Skyhawk",
	"Mirage",
	"Hellcat",
	"Helldiver",
	"Violator",
	"Corvette",
	"Interceptor",
	"Etendard",
	"Corsair",
	"Crusader",
	"Jaguar",
	"Harrier",
	"Phantom",
	"Hatsutaka",
	"Knight",
	"Paladin",
	"Messenger",
	"Seraphin",
	"Prophet",
	"Sage",
	"Guardian",
	"Overseer",
	"Nemesis",
	"Infidel",
	"Relentless",
	"Defiler",
	"Courageous",
	"Intangible",
	"Omnipotent",
	"Menace",
	"Invincible",
	"Invincible",
	"Invincible",
	"Invincible",
	"Invincible",
	"Invincible",
	"Invincible",
	"Invincible",
	"Wasp I",
	"Wasp II",
	"Wasp III",
	"Wasp IV",
	"Wasp V",
	"Wasp VI",
	"Wasp VII",
	"Wasp VIII",
	"Hornet I",
	"Hornet II",
	"Hornet III",
	"Hornet IV",
	"Hornet V",
	"Hornet VI",
	"Hornet VII",
	"Hornet VIII",
	"Spider I",
	"Spider II",
	"Spider III",
	"Spider IV",
	"Spider V",
	"Spider VI",
	"Spider VII",
	"Spider VIII",
	"Scorpion I",
	"Scorpion II",
	"Scorpion III",
	"Scorpion IV",
	"Scorpion V",
	"Scorpion VI",
	"Scorpion VII",
	"Scorpion VIII",
	"Widow I",
	"Widow II",
	"Widow III",
	"Widow IV",
	"Widow V",
	"Widow VI",
	"Widow VII",
	"Widow VIII",
	"Tarantula",
	"Tarantula",
	"Tarantula",
	"Tarantula",
	"Tarantula",
	"Tarantula",
	"Tarantula",
	"Tarantula",
	"Gatherer I",
	"Gatherer II",
	"Gatherer III",
	"Gatherer IV",
	"Gatherer V",
	"Gatherer VI",
	"Gatherer VII",
	"Gatherer VIII",
	"Ravager I",
	"Ravager II",
	"Ravager III",
	"Ravager IV",
	"Ravager V",
	"Ravager VI",
	"Ravager VII",
	"Ravager VIII",
	"Destructor I",
	"Destructor II",
	"Destructor III",
	"Destructor IV",
	"Destructor V",
	"Destructor VI",
	"Destructor VII",
	"Destructor VIII",
	"Tormentor I",
	"Tormentor II",
	"Tormentor III",
	"Tormentor IV",
	"Tormentor V",
	"Tormentor VI",
	"Tormentor VII",
	"Tormentor VIII",
	"Devastator I",
	"Devastator II",
	"Devastator III",
	"Devastator IV",
	"Devastator V",
	"Devastator VI",
	"Devastator VII",
	"Devastator VIII",
	"Annihilator",
	"Annihilator",
	"Annihilator",
	"Annihilator",
	"Annihilator",
	"Annihilator",
	"Annihilator",
	"Annihilator",
	"Bobcat I",
	"Bobcat II",
	"Bobcat III",
	"Bobcat IV",
	"Bobcat V",
	"Bobcat VI",
	"Bobcat VII",
	"Bobcat VIII",
	"Griffin I",
	"Griffin II",
	"Griffin III",
	"Griffin IV",
	"Griffin V",
	"Griffin VI",
	"Griffin VII",
	"Griffin VIII",
	"Lynx I",
	"Lynx II",
	"Lynx III",
	"Lynx IV",
	"Lynx V",
	"Lynx VI",
	"Lynx VII",
	"Lynx VIII",
	"Panther I",
	"Panther II",
	"Panther III",
	"Panther IV",
	"Panther V",
	"Panther VI",
	"Panther VII",
	"Panther VIII",
	"Warcat I",
	"Warcat II",
	"Warcat III",
	"Warcat IV",
	"Warcat V",
	"Warcat VI",
	"Warcat VII",
	"Warcat VIII",
	"Sabretooth",
	"Sabretooth",
	"Sabretooth",
	"Sabretooth",
	"Sabretooth",
	"Sabretooth",
	"Sabretooth",
	"Sabretooth",
	"Escort I",
	"Escort II",
	"Escort III",
	"Escort IV",
	"Escort V",
	"Escort VI",
	"Escort VII",
	"Escort VIII",
	"Courier I",
	"Courier II",
	"Courier III",
	"Courier IV",
	"Courier V",
	"Courier VI",
	"Courier VII",
	"Courier VIII",
	"Corvette I",
	"Corvette II",
	"Corvette III",
	"Corvette IV",
	"Corvette V",
	"Corvette VI",
	"Corvette VII",
	"Corvette VIII",
	"Fighter I",
	"Fighter II",
	"Fighter III",
	"Fighter IV",
	"Fighter V",
	"Fighter VI",
	"Fighter VII",
	"Fighter VIII",
	"War Ship I",
	"War Ship II",
	"War Ship III",
	"War Ship IV",
	"War Ship V",
	"War Ship VI",
	"War Ship VII",
	"War Ship VIII",
	"Dreadnought",
	"Dreadnought",
	"Dreadnought",
	"Dreadnought",
	"Dreadnought",
	"Dreadnought",
	"Dreadnought",
	"Dreadnought",
	"Gila I",
	"Gila II",
	"Gila III",
	"Chameleon",
	"Monitor",
	"Iguana",
	"Coral Snake",
	"King Snake",
	"Boa I",
	"Boa II",
	"Boa III",
	"Boa IV",
	"Boa V",
	"Boa VI",
	"Anaconda",
	"Python",
	"Cobra I",
	"Cobra II",
	"Cobra III",
	"Cobra IV",
	"Cobra V",
	"Cobra VI",
	"Cobra VII",
	"Cobra VIII",
	"Viper I",
	"Viper II",
	"Viper III",
	"Viper IV",
	"Viper V",
	"Viper VI",
	"Viper VII",
	"Viper VIII",
	"King Cobra I",
	"King Cobra II",
	"King Cobra III",
	"King Cobra IV",
	"King Cobra V",
	"King Cobra VI",
	"King Cobra VII",
	"King Cobra VIII",
	"Venom",
	"Venom",
	"Venom",
	"Venom",
	"Venom",
	"Venom",
	"Venom",
	"Dragon",
	"Nexus I",
	"Nexus II",
	"Nexus III",
	"Nexus IV",
	"Nexus V",
	"Nexus VI",
	"Nexus VII",
	"Nexus VIII",
	"Thunder I",
	"Thunder II",
	"Thunder III",
	"Thunder IV",
	"Thunder V",
	"Thunder VI",
	"Thunder VII",
	"Thunder VIII",
	"Lightning I",
	"Lightning II",
	"Lightning III",
	"Lightning IV",
	"Lightning V",
	"Lightning VI",
	"Lightning VII",
	"Lightning VIII",
	"Fury I",
	"Fury II",
	"Fury III",
	"Fury IV",
	"Fury V",
	"Fury VI",
	"Fury VII",
	"Fury VIII",
	"Tornado I",
	"Tornado II",
	"Tornado III",
	"Tornado IV",
	"Tornado V",
	"Tornado VI",
	"Tornado VII",
	"Tornado VIII",
	"Armageddon",
	"Armageddon",
	"Armageddon",
	"Armageddon",
	"Armageddon",
	"Armageddon",
	"Armageddon",
	"Armageddon",
	"Piranha I",
	"Piranha II",
	"Piranha III",
	"Piranha IV",
	"Piranha V",
	"Piranha VI",
	"Piranha VII",
	"Piranha VIII",
	"Stingray I",
	"Stingray II",
	"Stingray III",
	"Stingray IV",
	"Stingray V",
	"Stingray VI",
	"Stingray VII",
	"Stingray VIII",
	"Manta I",
	"Manta II",
	"Manta III",
	"Manta IV",
	"Manta V",
	"Manta VI",
	"Manta VII",
	"Manta VIII",
	"Morey I",
	"Morey II",
	"Morey III",
	"Morey IV",
	"Morey V",
	"Morey VI",
	"Morey VII",
	"Morey VIII",
	"Barracuda I",
	"Barracuda II",
	"Barracuda III",
	"Barracuda IV",
	"Barracuda V",
	"Barracuda VI",
	"Barracuda VII",
	"Barracuda VIII",
	"Kracon",
	"Orca",
	"Shark",
	"Shark",
	"Shark",
	"Shark",
	"Shark",
	"Shark",
	"Raider",
	"Raider",
	"Raider",
	"Raider",
	"Raider",
	"Raider",
	"Raider",
	"Raider",
	"Marauder",
	"Marauder",
	"Marauder",
	"Marauder",
	"Marauder",
	"Marauder",
	"Marauder",
	"Marauder",
	"Intruder",
	"Intruder",
	"Intruder",
	"Intruder",
	"Intruder",
	"Intruder",
	"Intruder",
	"Intruder",
	"Interdictor",
	"Interdictor",
	"Interdictor",
	"Interdictor",
	"Interdictor",
	"Interdictor",
	"Interdictor",
	"Interdictor",
	"Harbinger",
	"Harbinger",
	"Harbinger",
	"Harbinger",
	"Harbinger",
	"Harbinger",
	"Harbinger",
	"Harbinger",
	"Avenger",
	"Avenger",
	"Avenger",
	"Avenger",
	"Avenger",
	"Avenger",
	"Avenger",
	"Avenger",
}
